export interface Flight {
  id: number;
  airline: string;
  flightNumber: string;
  departure: {
    airport: string;
    code: string;
    time: string;
    city: string;
  };
  arrival: {
    airport: string;
    code: string;
    time: string;
    city: string;
  };
  duration: string;
  stops: number;
  stopCity?: string;
  aircraft: string;
  terminal: string;
  price: number;
  cabin: string;
  baggage: string;
  refundable: boolean;
  seatsAvailable: number;
  rating: number;
}

// Ensure your interface is exported
export interface Seat {
  id: string;
  row: number;
  col: string;
  type: 'available' | 'occupied' | 'premium' | 'selected';
  price?: number;
}

// Ensure your extras array is exported
export const extras = [
  { id: 1, name: 'Extra Baggage', price: 30, icon: 'briefcase', description: '...' },
  // ... rest of your extras data
];

// src/lib/data.ts

export interface Seat {
  id: string;
  row: number;
  col: string;
  type: 'available' | 'occupied' | 'premium' | 'selected';
  price?: number;
}

// Make sure "export" is written right here:
export const generateSeats = (): Seat[] => {
  const rows = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  const cols = ['A', 'B', 'C', 'D', 'E', 'F'];
  const seats: Seat[] = [];

  rows.forEach((row) => {
    cols.forEach((col) => {
      // Logic to determine seat type/pricing rules
      const isPremium = row <= 2; 
      const isOccupied = Math.random() < 0.2; // 20% random occupancy

      seats.push({
        id: `${row}${col}`,
        row,
        col,
        type: isOccupied ? 'occupied' : isPremium ? 'premium' : 'available',
        price: isPremium ? 45 : 25,
      });
    });
  });

  return seats;
};

// booking opyions

// src/lib/data.ts

export interface BookingFlightInfo {
  flightNumber: string;
  airline: string;
  departure: {
    code: string;
  };
  arrival: {
    code: string;
  };
}

export interface BookingData {
  id: string;
  flightNumber: string;
  passengerName: string;
  date: string;
  amount: number;
  total: number;
  passengers: number;
  status: 'upcoming' | 'completed' | 'confirmed' | 'pending' | 'cancelled';
  flight: BookingFlightInfo;
}

export const bookings: BookingData[] = [
  {
    id: "BK-8742",
    flightNumber: "AA-124",
    passengerName: "John Doe",
    date: "2026-07-15",
    amount: 320,
    total: 320,
    passengers: 1,
    status: "upcoming",
    flight: {
      flightNumber: "AA-124",
      airline: "American Airlines",
      departure: { code: "LAX" },
      arrival: { code: "JFK" },
    },
  },
  {
    id: "BK-3921",
    flightNumber: "DL-892",
    passengerName: "Jane Smith",
    date: "2026-07-18",
    amount: 450,
    total: 450,
    passengers: 2,
    status: "completed",
    flight: {
      flightNumber: "DL-892",
      airline: "Delta",
      departure: { code: "ATL" },
      arrival: { code: "LHR" },
    },
  }
];

export interface NotificationData {
  id: string;
  title: string;
  message: string;
  time: string;
  read: boolean;
}

export const notifications: NotificationData[] = [
  { id: '1', title: 'Check-in Reminder', message: 'Your check-in opens in 24 hours.', time: '2h ago', read: false },
  { id: '2', title: 'New Flight Offer', message: 'Save 20% on flights to Dubai.', time: '1d ago', read: true },
  { id: '3', title: 'Loyalty Bonus', message: 'You earned 5,000 bonus miles.', time: '3d ago', read: true },
];

export interface AdminStat {
  label: string;
  value: string;
  icon: string;
  change: string;
}

export const adminStats: AdminStat[] = [
  { label: 'Total Bookings', value: '1,240', icon: 'ticket', change: '+5.8%' },
  { label: 'Revenue', value: '$1.8M', icon: 'dollar-sign', change: '+12.4%' },
  { label: 'Active Customers', value: '18.2K', icon: 'users', change: '+3.2%' },
  { label: 'On Time Rate', value: '92%', icon: 'plane', change: '+1.1%' },
];


export const flights: Flight[] = [
  // ==========================================
  // EMIRATES (10 Unique Destinations)
  // ==========================================
  {
    id: 1,
    airline: 'Emirates',
    flightNumber: 'EK202',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '08:20', city: 'Dubai' },
    arrival: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '14:20', city: 'New York' },
    duration: '14h 00m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T3',
    price: 1350,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 6,
    rating: 4.9,
  },
  {
    id: 2,
    airline: 'Emirates',
    flightNumber: 'EK001',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '07:45', city: 'Dubai' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '12:20', city: 'London' },
    duration: '7h 35m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T3',
    price: 540,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 18,
    rating: 4.8,
  },
  {
    id: 3,
    airline: 'Emirates',
    flightNumber: 'EK318',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '02:50', city: 'Dubai' },
    arrival: { airport: 'Narita', code: 'NRT', time: '17:35', city: 'Tokyo' },
    duration: '9h 45m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 890,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 14,
    rating: 4.7,
  },
  {
    id: 4,
    airline: 'Emirates',
    flightNumber: 'EK073',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '09:40', city: 'Dubai' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '14:50', city: 'Paris' },
    duration: '7h 10m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T3',
    price: 2450,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 2,
    rating: 4.9,
  },
  {
    id: 5,
    airline: 'Emirates',
    flightNumber: 'EK412',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '10:15', city: 'Dubai' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '06:05+1', city: 'Sydney' },
    duration: '13h 50m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1210,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.8,
  },
  {
    id: 6,
    airline: 'Emirates',
    flightNumber: 'EK510',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '23:00', city: 'Dubai' },
    arrival: { airport: 'Indira Gandhi Intl', code: 'DEL', time: '04:10+1', city: 'New Delhi' },
    duration: '3h 40m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 380,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 22,
    rating: 4.6,
  },
  {
    id: 7,
    airline: 'Emirates',
    flightNumber: 'EK701',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '04:00', city: 'Dubai' },
    arrival: { airport: 'Sir Seewoosagur Ramgoolam', code: 'MRU', time: '10:45', city: 'Mauritius' },
    duration: '6h 45m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T3',
    price: 930,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 11,
    rating: 4.7,
  },
  {
    id: 8,
    airline: 'Emirates',
    flightNumber: 'EK241',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '18:20', city: 'Dubai' },
    arrival: { airport: 'Ministro Pistarini', code: 'EZE', time: '08:40+1', city: 'Buenos Aires' },
    duration: '19h 20m',
    stops: 1,
    stopCity: 'Rio de Janeiro',
    aircraft: 'Boeing 777-200LR',
    terminal: 'T3',
    price: 1620,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 4,
    rating: 4.7,
  },
  {
    id: 9,
    airline: 'Emirates',
    flightNumber: 'EK131',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '16:55', city: 'Dubai' },
    arrival: { airport: 'Domodedovo', code: 'DME', time: '21:15', city: 'Moscow' },
    duration: '5h 20m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1100,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: false,
    seatsAvailable: 3,
    rating: 4.5,
  },
  {
    id: 10,
    airline: 'Emirates',
    flightNumber: 'EK432',
    departure: { airport: 'Dubai Intl', code: 'DXB', time: '02:15', city: 'Dubai' },
    arrival: { airport: 'Brisbane Airport', code: 'BNE', time: '00:40+1', city: 'Brisbane' },
    duration: '16h 25m',
    stops: 1,
    stopCity: 'Singapore',
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1390,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 6,
    rating: 4.8,
  },

  // ==========================================
  // QATAR AIRWAYS (10 Unique Destinations)
  // ==========================================
  {
    id: 11,
    airline: 'Qatar Airways',
    flightNumber: 'QR701',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '08:15', city: 'Doha' },
    arrival: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '15:15', city: 'New York' },
    duration: '14h 30m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T8',
    price: 1550,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 4,
    rating: 4.9,
  },
  {
    id: 12,
    airline: 'Qatar Airways',
    flightNumber: 'QR003',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '07:45', city: 'Doha' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '13:15', city: 'London' },
    duration: '7h 30m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T4',
    price: 610,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 15,
    rating: 4.8,
  },
  {
    id: 13,
    airline: 'Qatar Airways',
    flightNumber: 'QR908',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '20:10', city: 'Doha' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '18:30+1', city: 'Sydney' },
    duration: '15h 20m',
    stops: 0,
    aircraft: 'Airbus A350-1000',
    terminal: 'T1',
    price: 1720,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.9,
  },
  {
    id: 14,
    airline: 'Qatar Airways',
    flightNumber: 'QR041',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '01:20', city: 'Doha' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '07:25', city: 'Paris' },
    duration: '7h 05m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T1',
    price: 580,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 12,
    rating: 4.7,
  },
  {
    id: 15,
    airline: 'Qatar Airways',
    flightNumber: 'QR812',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '06:45', city: 'Doha' },
    arrival: { airport: 'Haneda', code: 'HND', time: '22:40', city: 'Tokyo' },
    duration: '9h 55m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 810,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 9,
    rating: 4.8,
  },
  {
    id: 16,
    airline: 'Qatar Airways',
    flightNumber: 'QR1363',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '02:10', city: 'Doha' },
    arrival: { airport: 'Jomo Kenyatta Intl', code: 'NBO', time: '07:40', city: 'Nairobi' },
    duration: '5h 30m',
    stops: 0,
    aircraft: 'Airbus A320-200',
    terminal: 'T1',
    price: 490,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 8,
    rating: 4.6,
  },
  {
    id: 17,
    airline: 'Qatar Airways',
    flightNumber: 'QR570',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '19:30', city: 'Doha' },
    arrival: { airport: 'Chhatrapati Shivaji Intl', code: 'BOM', time: '02:00+1', city: 'Mumbai' },
    duration: '4h 00m',
    stops: 0,
    aircraft: 'Boeing 787-8',
    terminal: 'T2',
    price: 410,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 16,
    rating: 4.7,
  },
  {
    id: 18,
    airline: 'Qatar Airways',
    flightNumber: 'QR743',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '08:00', city: 'Doha' },
    arrival: { airport: 'Logan Intl', code: 'BOS', time: '14:30', city: 'Boston' },
    duration: '13h 30m',
    stops: 0,
    aircraft: 'Airbus A350-1000',
    terminal: 'TE',
    price: 2300,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 1,
    rating: 4.9,
  },
  {
    id: 19,
    airline: 'Qatar Airways',
    flightNumber: 'QR067',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '07:50', city: 'Doha' },
    arrival: { airport: 'Frankfurt Airport', code: 'FRA', time: '13:20', city: 'Frankfurt' },
    duration: '6h 30m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T1',
    price: 1290,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: false,
    seatsAvailable: 4,
    rating: 4.7,
  },
  {
    id: 20,
    airline: 'Qatar Airways',
    flightNumber: 'QR946',
    departure: { airport: 'Hamad Intl', code: 'DOH', time: '02:30', city: 'Doha' },
    arrival: { airport: 'Ngurah Rai Intl', code: 'DPS', time: '17:20', city: 'Bali' },
    duration: '11h 50m',
    stops: 1,
    stopCity: 'Singapore',
    aircraft: 'Boeing 787-9',
    terminal: 'T1',
    price: 1180,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 3,
    rating: 4.8,
  },

  // ==========================================
  // BRITISH AIRWAYS (10 Unique Destinations)
  // ==========================================
  {
    id: 21,
    airline: 'British Airways',
    flightNumber: 'BA175',
    departure: { airport: 'Heathrow', code: 'LHR', time: '11:20', city: 'London' },
    arrival: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '14:25', city: 'New York' },
    duration: '8h 05m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T5',
    price: 510,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 14,
    rating: 4.3,
  },
  {
    id: 22,
    airline: 'British Airways',
    flightNumber: 'BA269',
    departure: { airport: 'Heathrow', code: 'LHR', time: '15:00', city: 'London' },
    arrival: { airport: 'Los Angeles Intl', code: 'LAX', time: '18:15', city: 'Los Angeles' },
    duration: '11h 15m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T5',
    price: 1320,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 6,
    rating: 4.4,
  },
  {
    id: 23,
    airline: 'British Airways',
    flightNumber: 'BA015',
    departure: { airport: 'Heathrow', code: 'LHR', time: '21:35', city: 'London' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '05:15+2', city: 'Sydney' },
    duration: '22h 40m',
    stops: 1,
    stopCity: 'Singapore',
    aircraft: 'Boeing 787-9',
    terminal: 'T5',
    price: 1490,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: false,
    seatsAvailable: 4,
    rating: 4.5,
  },
  {
    id: 24,
    airline: 'British Airways',
    flightNumber: 'BA117',
    departure: { airport: 'Heathrow', code: 'LHR', time: '08:30', city: 'London' },
    arrival: { airport: 'Dulles Intl', code: 'IAD', time: '11:30', city: 'Washington' },
    duration: '8h 00m',
    stops: 0,
    aircraft: 'Boeing 777-200',
    terminal: 'T5',
    price: 590,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 11,
    rating: 4.2,
  },
  {
    id: 25,
    airline: 'British Airways',
    flightNumber: 'BA346',
    departure: { airport: 'Heathrow', code: 'LHR', time: '13:15', city: 'London' },
    arrival: { airport: 'Cote d\'Azur', code: 'NCE', time: '16:25', city: 'Nice' },
    duration: '2h 10m',
    stops: 0,
    aircraft: 'Airbus A320neo',
    terminal: 'T3',
    price: 120,
    cabin: 'Economy',
    baggage: 'Carry-on only',
    refundable: false,
    seatsAvailable: 24,
    rating: 4.1,
  },
  {
    id: 26,
    airline: 'British Airways',
    flightNumber: 'BA572',
    departure: { airport: 'Heathrow', code: 'LHR', time: '07:20', city: 'London' },
    arrival: { airport: 'Linate Airport', code: 'LIN', time: '10:20', city: 'Milan' },
    duration: '2h 00m',
    stops: 0,
    aircraft: 'Airbus A321neo',
    terminal: 'T5',
    price: 160,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 18,
    rating: 4.2,
  },
  {
    id: 27,
    airline: 'British Airways',
    flightNumber: 'BA247',
    departure: { airport: 'Heathrow', code: 'LHR', time: '22:05', city: 'London' },
    arrival: { airport: 'Guarulhos Intl', code: 'GRU', time: '05:55+1', city: 'São Paulo' },
    duration: '11h 50m',
    stops: 0,
    aircraft: 'Boeing 787-10',
    terminal: 'T5',
    price: 1050,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.4,
  },
  {
    id: 28,
    airline: 'British Airways',
    flightNumber: 'BA057',
    departure: { airport: 'Heathrow', code: 'LHR', time: '21:25', city: 'London' },
    arrival: { airport: 'O.R. Tambo Intl', code: 'JNB', time: '08:45+1', city: 'Johannesburg' },
    duration: '11h 20m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T5',
    price: 760,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 9,
    rating: 4.3,
  },
  {
    id: 29,
    airline: 'British Airways',
    flightNumber: 'BA142',
    departure: { airport: 'Heathrow', code: 'LHR', time: '09:30', city: 'London' },
    arrival: { airport: 'Indira Gandhi Intl', code: 'DEL', time: '22:50', city: 'New Delhi' },
    duration: '8h 50m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T5',
    price: 1750,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 2,
    rating: 4.5,
  },
  {
    id: 30,
    airline: 'British Airways',
    flightNumber: 'BA207',
    departure: { airport: 'Heathrow', code: 'LHR', time: '10:40', city: 'London' },
    arrival: { airport: 'Lynden Pindling Intl', code: 'NAS', time: '18:15', city: 'Nassau' },
    duration: '10h 35m',
    stops: 1,
    stopCity: 'Grand Cayman',
    aircraft: 'Boeing 777-200',
    terminal: 'T5',
    price: 640,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 7,
    rating: 4.2,
  },

  // ==========================================
  // SINGAPORE AIRLINES (10 Unique Destinations)
  // ==========================================
  {
    id: 31,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ022',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '23:35', city: 'Singapore' },
    arrival: { airport: 'Newark Liberty', code: 'EWR', time: '06:00+1', city: 'New York' },
    duration: '18h 25m',
    stops: 0,
    aircraft: 'Airbus A350-900ULR',
    terminal: 'T3',
    price: 1950,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 4,
    rating: 5.0,
  },
  {
    id: 32,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ322',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '23:30', city: 'Singapore' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '05:55+1', city: 'London' },
    duration: '13h 25m',
    stops: 0,
    aircraft: 'Airbus A380-800',
    terminal: 'T3',
    price: 2600,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 2,
    rating: 4.9,
  },
  {
    id: 33,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ638',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '23:55', city: 'Singapore' },
    arrival: { airport: 'Narita', code: 'NRT', time: '07:30+1', city: 'Tokyo' },
    duration: '6h 35m',
    stops: 0,
    aircraft: 'Boeing 787-10',
    terminal: 'T3',
    price: 590,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 15,
    rating: 4.8,
  },
  {
    id: 34,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ231',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '00:45', city: 'Singapore' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '10:25', city: 'Sydney' },
    duration: '7h 40m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1100,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 8,
    rating: 4.9,
  },
  {
    id: 35,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ336',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '00:15', city: 'Singapore' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '07:15', city: 'Paris' },
    duration: '13h 00m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T3',
    price: 680,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 14,
    rating: 4.8,
  },
  {
    id: 36,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ424',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '19:00', city: 'Singapore' },
    arrival: { airport: 'Chhatrapati Shivaji Intl', code: 'BOM', time: '22:10', city: 'Mumbai' },
    duration: '5h 40m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T3',
    price: 430,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 20,
    rating: 4.7,
  },
  {
    id: 37,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ830',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '09:30', city: 'Singapore' },
    arrival: { airport: 'Pudong Intl', code: 'PVG', time: '15:05', city: 'Shanghai' },
    duration: '5h 35m',
    stops: 0,
    aircraft: 'Boeing 787-10',
    terminal: 'T3',
    price: 520,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 11,
    rating: 4.6,
  },
  {
    id: 38,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ285',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '22:30', city: 'Singapore' },
    arrival: { airport: 'Auckland Airport', code: 'AKL', time: '12:45+1', city: 'Auckland' },
    duration: '9h 15m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1350,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.9,
  },
  {
    id: 39,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ494',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '01:20', city: 'Singapore' },
    arrival: { airport: 'Dubai Intl', code: 'DXB', time: '04:50', city: 'Dubai' },
    duration: '7h 30m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T3',
    price: 980,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: false,
    seatsAvailable: 6,
    rating: 4.8,
  },
  {
    id: 40,
    airline: 'Singapore Airlines',
    flightNumber: 'SQ211',
    departure: { airport: 'Changi Airport', code: 'SIN', time: '10:30', city: 'Singapore' },
    arrival: { airport: 'Melbourne Airport', code: 'MEL', time: '19:45', city: 'Melbourne' },
    duration: '7h 15m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T3',
    price: 510,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 19,
    rating: 4.7,
  },

  // ==========================================
  // LUFTHANSA (10 Unique Destinations)
  // ==========================================
  {
    id: 41,
    airline: 'Lufthansa',
    flightNumber: 'LH400',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '10:55', city: 'Frankfurt' },
    arrival: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '13:30', city: 'New York' },
    duration: '8h 35m',
    stops: 0,
    aircraft: 'Boeing 747-8i',
    terminal: 'T1',
    price: 590,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 25,
    rating: 4.4,
  },
  {
    id: 42,
    airline: 'Lufthansa',
    flightNumber: 'LH900',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '07:30', city: 'Frankfurt' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '08:10', city: 'London' },
    duration: '1h 40m',
    stops: 0,
    aircraft: 'Airbus A321neo',
    terminal: 'T1',
    price: 180,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 30,
    rating: 4.2,
  },
  {
    id: 43,
    airline: 'Lufthansa',
    flightNumber: 'LH716',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '18:15', city: 'Frankfurt' },
    arrival: { airport: 'Haneda', code: 'HND', time: '12:15+1', city: 'Tokyo' },
    duration: '11h 00m',
    stops: 0,
    aircraft: 'Boeing 747-8i',
    terminal: 'T1',
    price: 1450,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 7,
    rating: 4.6,
  },
  {
    id: 44,
    airline: 'Lufthansa',
    flightNumber: 'LH630',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '14:20', city: 'Frankfurt' },
    arrival: { airport: 'Dubai Intl', code: 'DXB', time: '22:55', city: 'Dubai' },
    duration: '6h 35m',
    stops: 0,
    aircraft: 'Airbus A330-300',
    terminal: 'T1',
    price: 1120,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.5,
  },
  {
    id: 45,
    airline: 'Lufthansa',
    flightNumber: 'LH456',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '10:15', city: 'Frankfurt' },
    arrival: { airport: 'Los Angeles Intl', code: 'LAX', time: '12:50', city: 'Los Angeles' },
    duration: '11h 35m',
    stops: 0,
    aircraft: 'Airbus A340-300',
    terminal: 'T1',
    price: 2200,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 3,
    rating: 4.7,
  },
  {
    id: 46,
    airline: 'Lufthansa',
    flightNumber: 'LH506',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '22:05', city: 'Frankfurt' },
    arrival: { airport: 'Guarulhos Intl', code: 'GRU', time: '04:55+1', city: 'São Paulo' },
    duration: '11h 50m',
    stops: 0,
    aircraft: 'Boeing 747-8i',
    terminal: 'T1',
    price: 890,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 14,
    rating: 4.3,
  },
  {
    id: 47,
    airline: 'Lufthansa',
    flightNumber: 'LH778',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '21:55', city: 'Frankfurt' },
    arrival: { airport: 'Changi Airport', code: 'SIN', time: '16:15+1', city: 'Singapore' },
    duration: '12h 20m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T1',
    price: 1390,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 6,
    rating: 4.5,
  },
  {
    id: 48,
    airline: 'Lufthansa',
    flightNumber: 'LH572',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '22:00', city: 'Frankfurt' },
    arrival: { airport: 'O.R. Tambo Intl', code: 'JNB', time: '08:30+1', city: 'Johannesburg' },
    duration: '10h 30m',
    stops: 0,
    aircraft: 'Boeing 747-8i',
    terminal: 'T1',
    price: 740,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 18,
    rating: 4.4,
  },
  {
    id: 49,
    airline: 'Lufthansa',
    flightNumber: 'LH1050',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '09:00', city: 'Frankfurt' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '10:15', city: 'Paris' },
    duration: '1h 15m',
    stops: 0,
    aircraft: 'Airbus A320neo',
    terminal: 'T1',
    price: 140,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 22,
    rating: 4.1,
  },
  {
    id: 50,
    airline: 'Lufthansa',
    flightNumber: 'LH430',
    departure: { airport: 'Frankfurt Airport', code: 'FRA', time: '13:45', city: 'Frankfurt' },
    arrival: { airport: 'O\'Hare Intl', code: 'ORD', time: '15:50', city: 'Chicago' },
    duration: '9h 05m',
    stops: 1,
    stopCity: 'Munich',
    aircraft: 'Airbus A350-900',
    terminal: 'T1',
    price: 610,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 9,
    rating: 4.3,
  },

  // ==========================================
  // DELTA AIR LINES (10 Unique Destinations)
  // ==========================================
  {
    id: 51,
    airline: 'Delta Air Lines',
    flightNumber: 'DL001',
    departure: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '19:30', city: 'New York' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '07:45+1', city: 'London' },
    duration: '7h 15m',
    stops: 0,
    aircraft: 'Boeing 767-400ER',
    terminal: 'T4',
    price: 499,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 15,
    rating: 4.5,
  },
  {
    id: 52,
    airline: 'Delta Air Lines',
    flightNumber: 'DL264',
    departure: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '17:45', city: 'New York' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '07:10+1', city: 'Paris' },
    duration: '7h 25m',
    stops: 0,
    aircraft: 'Airbus A330-900neo',
    terminal: 'T4',
    price: 1250,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 8,
    rating: 4.7,
  },
  {
    id: 53,
    airline: 'Delta Air Lines',
    flightNumber: 'DL120',
    departure: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '20:00', city: 'New York' },
    arrival: { airport: 'Leonardo da Vinci', code: 'FCO', time: '10:30+1', city: 'Rome' },
    duration: '8h 30m',
    stops: 0,
    aircraft: 'Airbus A330-300',
    terminal: 'T4',
    price: 580,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 12,
    rating: 4.6,
  },
  {
    id: 54,
    airline: 'Delta Air Lines',
    flightNumber: 'DL275',
    departure: { airport: 'Detroit Metro', code: 'DTW', time: '12:30', city: 'Detroit' },
    arrival: { airport: 'Haneda', code: 'HND', time: '15:15+1', city: 'Tokyo' },
    duration: '13h 45m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'EM',
    price: 1410,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 4,
    rating: 4.8,
  },
  {
    id: 55,
    airline: 'Delta Air Lines',
    flightNumber: 'DL106',
    departure: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '21:15', city: 'New York' },
    arrival: { airport: 'Frankfurt Airport', code: 'FRA', time: '11:10+1', city: 'Frankfurt' },
    duration: '7h 55m',
    stops: 0,
    aircraft: 'Boeing 767-300ER',
    terminal: 'T4',
    price: 520,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 17,
    rating: 4.4,
  },
  {
    id: 56,
    airline: 'Delta Air Lines',
    flightNumber: 'DL042',
    departure: { airport: 'Hartsfield-Jackson', code: 'ATL', time: '16:45', city: 'Atlanta' },
    arrival: { airport: 'Schiphol', code: 'AMS', time: '07:20+1', city: 'Amsterdam' },
    duration: '8h 35m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'TI',
    price: 1350,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: false,
    seatsAvailable: 5,
    rating: 4.7,
  },
  {
    id: 57,
    airline: 'Delta Air Lines',
    flightNumber: 'DL201',
    departure: { airport: 'Hartsfield-Jackson', code: 'ATL', time: '23:05', city: 'Atlanta' },
    arrival: { airport: 'O.R. Tambo Intl', code: 'JNB', time: '21:10+1', city: 'Johannesburg' },
    duration: '16h 05m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'TI',
    price: 890,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 9,
    rating: 4.6,
  },
  {
    id: 58,
    airline: 'Delta Air Lines',
    flightNumber: 'DL093',
    departure: { airport: 'Los Angeles Intl', code: 'LAX', time: '22:45', city: 'Los Angeles' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '06:50+2', city: 'Sydney' },
    duration: '15h 05m',
    stops: 0,
    aircraft: 'Airbus A350-900',
    terminal: 'T3',
    price: 1550,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 3,
    rating: 4.8,
  },
  {
    id: 59,
    airline: 'Delta Air Lines',
    flightNumber: 'DL468',
    departure: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '08:00', city: 'New York' },
    arrival: { airport: 'Benito Juárez Intl', code: 'MEX', time: '12:30', city: 'Mexico City' },
    duration: '5h 30m',
    stops: 0,
    aircraft: 'Boeing 737-900ER',
    terminal: 'T4',
    price: 280,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 22,
    rating: 4.3,
  },
  {
    id: 60,
    airline: 'Delta Air Lines',
    flightNumber: 'DL187',
    departure: { airport: 'Seattle-Tacoma', code: 'SEA', time: '11:45', city: 'Seattle' },
    arrival: { airport: 'Incheon Intl', code: 'ICN', time: '15:20+1', city: 'Seoul' },
    duration: '11h 35m',
    stops: 1,
    stopCity: 'Portland',
    aircraft: 'Airbus A330-900neo',
    terminal: 'TS',
    price: 760,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 11,
    rating: 4.5,
  },

  // ==========================================
  // ANA - ALL NIPPON AIRWAYS (10 Destinations)
  // ==========================================
  {
    id: 61,
    airline: 'ANA',
    flightNumber: 'NH110',
    departure: { airport: 'Haneda', code: 'HND', time: '10:20', city: 'Tokyo' },
    arrival: { airport: 'John F. Kennedy Intl', code: 'JFK', time: '10:15', city: 'New York' },
    duration: '12h 55m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1650,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 5,
    rating: 4.9,
  },
  {
    id: 62,
    airline: 'ANA',
    flightNumber: 'NH211',
    departure: { airport: 'Haneda', code: 'HND', time: '11:40', city: 'Tokyo' },
    arrival: { airport: 'Heathrow', code: 'LHR', time: '16:20', city: 'London' },
    duration: '13h 40m',
    stops: 0,
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 2800,
    cabin: 'First',
    baggage: '3 checked bags',
    refundable: true,
    seatsAvailable: 2,
    rating: 5.0,
  },
  {
    id: 63,
    airline: 'ANA',
    flightNumber: 'NH801',
    departure: { airport: 'Narita', code: 'NRT', time: '18:05', city: 'Tokyo' },
    arrival: { airport: 'Changi Airport', code: 'SIN', time: '00:15+1', city: 'Singapore' },
    duration: '7h 10m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T1',
    price: 540,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 14,
    rating: 4.8,
  },
  {
    id: 64,
    airline: 'ANA',
    flightNumber: 'NH879',
    departure: { airport: 'Haneda', code: 'HND', time: '22:10', city: 'Tokyo' },
    arrival: { airport: 'Kingsford Smith', code: 'SYD', time: '08:30+1', city: 'Sydney' },
    duration: '9h 20m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T3',
    price: 1250,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 6,
    rating: 4.9,
  },
  {
    id: 65,
    airline: 'ANA',
    flightNumber: 'NH215',
    departure: { airport: 'Haneda', code: 'HND', time: '10:50', city: 'Tokyo' },
    arrival: { airport: 'Charles de Gaulle', code: 'CDG', time: '16:20', city: 'Paris' },
    duration: '12h 30m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T3',
    price: 690,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 18,
    rating: 4.7,
  },
  {
    id: 66,
    airline: 'ANA',
    flightNumber: 'NH815',
    departure: { airport: 'Narita', code: 'NRT', time: '17:15', city: 'Tokyo' },
    arrival: { airport: 'Suvarnabhumi Airport', code: 'BKK', time: '21:45', city: 'Bangkok' },
    duration: '5h 30m',
    stops: 0,
    aircraft: 'Boeing 787-10',
    terminal: 'T1',
    price: 410,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 23,
    rating: 4.8,
  },
  {
    id: 67,
    airline: 'ANA',
    flightNumber: 'NH851',
    departure: { airport: 'Haneda', code: 'HND', time: '09:45', city: 'Tokyo' },
    arrival: { airport: 'Taoyuan Intl', code: 'TPE', time: '12:15', city: 'Taipei' },
    duration: '3h 30m',
    stops: 0,
    aircraft: 'Boeing 787-8',
    terminal: 'T3',
    price: 360,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: true,
    seatsAvailable: 11,
    rating: 4.7,
  },
  {
    id: 68,
    airline: 'ANA',
    flightNumber: 'NH176',
    departure: { airport: 'Narita', code: 'NRT', time: '16:00', city: 'Tokyo' },
    arrival: { airport: 'Vancouver Intl', code: 'YVR', time: '08:40', city: 'Vancouver' },
    duration: '8h 40m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T1',
    price: 1180,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 4,
    rating: 4.8,
  },
  {
    id: 69,
    airline: 'ANA',
    flightNumber: 'NH829',
    departure: { airport: 'Narita', code: 'NRT', time: '18:20', city: 'Tokyo' },
    arrival: { airport: 'Tan Son Nhat Intl', code: 'SGN', time: '22:30', city: 'Ho Chi Minh City' },
    duration: '6h 10m',
    stops: 0,
    aircraft: 'Boeing 787-9',
    terminal: 'T1',
    price: 460,
    cabin: 'Economy',
    baggage: '1 checked bag',
    refundable: false,
    seatsAvailable: 8,
    rating: 4.6,
  },
  {
    id: 70,
    airline: 'ANA',
    flightNumber: 'NH203',
    departure: { airport: 'Haneda', code: 'HND', time: '00:10', city: 'Tokyo' },
    arrival: { airport: 'Frankfurt Airport', code: 'FRA', time: '05:30', city: 'Frankfurt' },
    duration: '12h 20m',
    stops: 1,
    stopCity: 'Osaka',
    aircraft: 'Boeing 777-300ER',
    terminal: 'T3',
    price: 1390,
    cabin: 'Business',
    baggage: '2 checked bags',
    refundable: true,
    seatsAvailable: 3,
    rating: 4.9,
  },
];