import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type ThemeMode = 'light' | 'dark';
// Look for this in your types/index.ts or global.d.ts
export type Language = 
  | "en" | "es" | "fr" | "de" | "it" | "pt" 
  | "nl" | "tr" | "sv" | "ru" | "ar" | "hi" 
  | "zh" | "ja" | "ko" | "vi";

type UiContextValue = {
  theme: ThemeMode;
  toggleTheme: () => void;
  setTheme: (theme: ThemeMode) => void;
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const UiContext = createContext<UiContextValue | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.flights': 'Flights',
    'nav.destinations': 'Destinations',
    'nav.deals': 'Deals',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.orderNow': 'Order Now',
    'nav.dashboard': 'Dashboard',
    'nav.signUp': 'Sign Up',
    'nav.lightMode': 'Light Mode',
    'nav.darkMode': 'Dark Mode',
    'nav.langLabel': 'EN',
    'nav.language': 'Language',
    'nav.languageSubtitle': 'Choose your preferred language',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'footer.fly': 'Fly',
    'footer.experience': 'Experience',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.bookFlight': 'Book a Flight',
    'footer.flightStatus': 'Flight Status',
    'footer.checkIn': 'Check-In',
    'footer.cabins': 'Cabins',
    'footer.dining': 'Dining',
    'footer.entertainment': 'Entertainment',
    'footer.lounges': 'Lounges',
    'footer.helpCenter': 'Help Center',
    'footer.contactUs': 'Contact Us',
    'footer.baggageInfo': 'Baggage Info',
    'footer.specialAssistance': 'Special Assistance',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookie': 'Cookie Policy',
    'footer.rights': '© 2025 SkyLux Airlines. All rights reserved.',
    'footer.privacyShort': 'Privacy',
    'footer.termsShort': 'Terms',
    'footer.cookiesShort': 'Cookies',
    'footer.sitemap': 'Sitemap',
    'hero.badge': 'Validated Manifest // Tier-1 Airline Matrix',
    'hero.titleLine1': 'Elevate Your',
    'hero.titleLine2': 'Global',
    'hero.highlight': 'Transit Matrix',
    'hero.subtitle': 'Provision dynamic commercial routing architectures across 500+ elite carriers. Secure algorithmic inventory access backed by custom multi-city concierge execution.',
    'destinations.eyebrow': 'Popular',
    'destinations.title': 'Explore Trending Destinations',
    'destinations.subtitle': 'Handpicked cities loved by our travelers this season.',
    'destinations.from': 'From',
    'deals.eyebrow': 'Limited Time',
    'deals.title': 'Featured Deals',
    'deals.endsIn': 'Ends in',
    'deals.from': 'From',
    'deals.to': 'To',
    'deals.bookNow': 'Book Now',
    'features.eyebrow': 'Enterprise Features',
    'features.title': 'Fly Smarter, Not Harder',
    'features.subtitle': 'Everything you need for a seamless luxury journey — engineered for modern travelers.',
    'features.placeholder': 'Search core capabilities...',
    'features.showing': 'Showing',
    'features.of': 'of',
    'features.options': 'options',
    'features.collapse': 'Collapse Overview',
    'features.viewAll': 'View All Capabilities',
    'features.none': 'No enterprise features found matching',
    'about.eyebrow': 'About',
    'about.title': 'A smarter way to fly',
    'about.subtitle': 'SkyLux was founded in 2018 to make world-class travel accessible. Today we serve 2M+ travelers across 190 countries with an obsession for detail and design.',
    'about.travelers': 'Travelers',
    'about.partners': 'Airline partners',
    'about.countries': 'Countries',
    'contact.eyebrow': 'Contact',
    'contact.title': "We're here 24/7",
    'contact.subtitle': 'Reach our concierge team any time — we typically reply in under 5 minutes.',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.hq': 'HQ',
    'contact.firstName': 'First name',
    'contact.lastName': 'Last name',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'services.eyebrow': 'Services',
    'services.title': 'Premium experiences, tailored to you',
    'services.subtitle': 'From priority boarding to bespoke itineraries, everything is designed around your journey.',
    'notFound.title': 'Page Not Found',
    'notFound.subtitle': 'The page you are looking for doesn’t exist or has been moved.',
    'notFound.home': 'Go Home',
    'auth.loginTitle': 'Welcome Back',
    'auth.loginSubtitle': 'Sign in to your SkyLux account',
    'auth.orContinue': 'or continue with email',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.noAccount': 'Don’t have an account?',
    'auth.signUp': 'Sign up',
    'auth.createAccountTitle': 'Create Account',
    'auth.createAccountSubtitle': 'Join SkyLux for exclusive benefits',
    'auth.orSignUpWithEmail': 'or sign up with email',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.passwordHint1': 'At least 8 characters',
    'auth.passwordHint2': 'One uppercase letter',
    'auth.passwordHint3': 'One number',
    'auth.termsPrefix': 'I agree to the',
    'auth.termsLink': 'Terms of Service',
    'auth.privacyLink': 'Privacy Policy',
    'auth.createAccount': 'Create Account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInLink': 'Sign in',
    'dashboard.member': 'SkyLux Member',
    'dashboard.sidebarTrips': 'My Trips',
    'dashboard.sidebarUpcoming': 'Upcoming Flights',
    'dashboard.sidebarRewards': 'Rewards',
    'dashboard.sidebarPassengers': 'Saved Passengers',
    'dashboard.sidebarPayments': 'Payments',
    'dashboard.sidebarNotifications': 'Notifications',
    'dashboard.sidebarSettings': 'Settings',
    'dashboard.signOut': 'Sign Out',
    'dashboard.welcome': 'Welcome back, John!',
    'dashboard.summary': 'Here’s what’s happening with your travel',
    'dashboard.totalTrips': 'Total Trips',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.skymiles': 'SkyMiles',
    'dashboard.rewards': 'Rewards',
    'dashboard.myTrips': 'My Trips',
    'dashboard.viewAll': 'View All',
    'dashboard.upcomingLabel': 'Upcoming',
    'dashboard.completedLabel': 'Completed',
    'dashboard.notifications': 'Notifications',
    'dashboard.adminTitle': 'Admin Dashboard',
    'dashboard.adminSubtitle': 'Manage your airline operations',
    'dashboard.last30Days': 'Last 30 days',
    'dashboard.tabOverview': 'Overview',
    'dashboard.tabFlights': 'Flights',
    'dashboard.tabBookings': 'Bookings',
    'dashboard.tabCustomers': 'Customers',
    'dashboard.tabSettings': 'Settings',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.cabinDistribution': 'Cabin Distribution',
    'dashboard.topRoutes': 'Top Routes',
    'dashboard.recentBookings': 'Recent Bookings',
    'dashboard.search': 'Search...',
    'dashboard.bookingId': 'Booking ID',
    'dashboard.route': 'Route',
    'dashboard.date': 'Date',
    'dashboard.passengers': 'Passengers',
    'dashboard.status': 'Status',
    'dashboard.amount': 'Amount',
    'dashboard.flightManagement': 'Flight Management',
    'dashboard.flightManagementSubtitle': 'Monitor fleet and schedule performance',
    'dashboard.noResults': 'No results found',
    'flights.sortCheapest': 'Cheapest',
    'flights.sortFastest': 'Fastest',
    'flights.sortBestValue': 'Best Value',
    'flights.stops': 'Stops',
    'flights.nonStop': 'Non-stop',
    'flights.oneStop': '1 Stop',
    'flights.multiStop': '2+ Stops',
    'flights.priceRange': 'Price Range',
    'flights.airlines': 'Airlines',
    'flights.cabinClass': 'Cabin Class',
    'flights.bookingOptions': 'Booking Options',
    'flights.refundableOnly': 'Refundable only',
    'flights.modifySearch': 'Modify Search',
    'flights.flightsFound': 'flights found',
    'flights.filters': 'Filters',
    'flights.perPerson': 'per person',
    'flights.select': 'Select',
    'flights.noFlights': 'No flights match your filters',
    'flights.clearFilters': 'Clear all filters',
    'flights.seatsLeft': 'seats left',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.flights': 'Vuelos',
    'nav.destinations': 'Destinos',
    'nav.deals': 'Ofertas',
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.signIn': 'Iniciar sesión',
    'nav.orderNow': 'Pedir ahora',
    'nav.dashboard': 'Panel',
    'nav.signUp': 'Registrarse',
    'nav.lightMode': 'Modo claro',
    'nav.darkMode': 'Modo oscuro',
    'nav.langLabel': 'ES',
    'nav.language': 'Idioma',
    'nav.languageSubtitle': 'Elige tu idioma preferido',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'footer.fly': 'Volar',
    'footer.experience': 'Experiencia',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.bookFlight': 'Reservar un vuelo',
    'footer.flightStatus': 'Estado del vuelo',
    'footer.checkIn': 'Registro',
    'footer.cabins': 'Cabinas',
    'footer.dining': 'Restauración',
    'footer.entertainment': 'Entretenimiento',
    'footer.lounges': 'Salones',
    'footer.helpCenter': 'Centro de ayuda',
    'footer.contactUs': 'Contáctanos',
    'footer.baggageInfo': 'Información de equipaje',
    'footer.specialAssistance': 'Asistencia especial',
    'footer.privacy': 'Política de privacidad',
    'footer.terms': 'Términos de servicio',
    'footer.cookie': 'Política de cookies',
    'footer.rights': '© 2025 SkyLux Airlines. Todos los derechos reservados.',
    'footer.privacyShort': 'Privacidad',
    'footer.termsShort': 'Términos',
    'footer.cookiesShort': 'Cookies',
    'footer.sitemap': 'Mapa del sitio',
    'hero.badge': 'Manifiesto validado // Matriz aérea de nivel 1',
    'hero.titleLine1': 'Eleva tu',
    'hero.titleLine2': 'transporte',
    'hero.highlight': 'global',
    'hero.subtitle': 'Proporciona rutas comerciales dinámicas en más de 500 aerolíneas premium. Acceso seguro a inventarios con ejecución personalizada de viajes multicity.',
    'destinations.eyebrow': 'Popular',
    'destinations.title': 'Explora los destinos más buscados',
    'destinations.subtitle': 'Ciudades seleccionadas por nuestros viajeros esta temporada.',
    'destinations.from': 'Desde',
    'deals.eyebrow': 'Tiempo limitado',
    'deals.title': 'Ofertas destacadas',
    'deals.endsIn': 'Termina en',
    'deals.from': 'Desde',
    'deals.to': 'Hasta',
    'deals.bookNow': 'Reservar',
    'features.eyebrow': 'Funciones empresariales',
    'features.title': 'Vuela más inteligente',
    'features.subtitle': 'Todo lo que necesitas para un viaje de lujo sin complicaciones — diseñado para viajeros modernos.',
    'features.placeholder': 'Buscar capacidades clave...',
    'features.showing': 'Mostrando',
    'features.of': 'de',
    'features.options': 'opciones',
    'features.collapse': 'Ocultar resumen',
    'features.viewAll': 'Ver todas las capacidades',
    'features.none': 'No se encontraron funciones empresariales que coincidan con',
    'about.eyebrow': 'Nosotros',
    'about.title': 'Una forma más inteligente de volar',
    'about.subtitle': 'SkyLux fue fundada en 2018 para hacer que los viajes de clase mundial sean accesibles. Hoy atendemos a más de 2M+ viajeros en 190 países con obsesión por el detalle y el diseño.',
    'about.travelers': 'Viajeros',
    'about.partners': 'Socios aéreos',
    'about.countries': 'Países',
    'contact.eyebrow': 'Contacto',
    'contact.title': 'Estamos aquí 24/7',
    'contact.subtitle': 'Contacta a nuestro equipo de concierge en cualquier momento; normalmente respondemos en menos de 5 minutos.',
    'contact.email': 'Correo',
    'contact.phone': 'Teléfono',
    'contact.hq': 'Sede',
    'contact.firstName': 'Nombre',
    'contact.lastName': 'Apellido',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar mensaje',
    'services.eyebrow': 'Servicios',
    'services.title': 'Experiencias premium, adaptadas a ti',
    'services.subtitle': 'Desde embarque prioritario hasta itinerarios a medida, todo está diseñado alrededor de tu viaje.',
    'notFound.title': 'Página no encontrada',
    'notFound.subtitle': 'La página que buscas no existe o se ha movido.',
    'notFound.home': 'Ir al inicio',
    'auth.loginTitle': 'Bienvenido de nuevo',
    'auth.loginSubtitle': 'Inicia sesión en tu cuenta de SkyLux',
    'auth.orContinue': 'o continúa con tu correo',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.rememberMe': 'Recuérdame',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.signIn': 'Iniciar sesión',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.signUp': 'Regístrate',
    'auth.createAccountTitle': 'Crear cuenta',
    'auth.createAccountSubtitle': 'Únete a SkyLux para obtener beneficios exclusivos',
    'auth.orSignUpWithEmail': 'o regístrate con correo',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.passwordHint1': 'Al menos 8 caracteres',
    'auth.passwordHint2': 'Una letra mayúscula',
    'auth.passwordHint3': 'Un número',
    'auth.termsPrefix': 'Acepto los',
    'auth.termsLink': 'Términos de servicio',
    'auth.privacyLink': 'Política de privacidad',
    'auth.createAccount': 'Crear cuenta',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.signInLink': 'Inicia sesión',
    'dashboard.member': 'Miembro de SkyLux',
    'dashboard.sidebarTrips': 'Mis viajes',
    'dashboard.sidebarUpcoming': 'Próximos vuelos',
    'dashboard.sidebarRewards': 'Recompensas',
    'dashboard.sidebarPassengers': 'Pasajeros guardados',
    'dashboard.sidebarPayments': 'Pagos',
    'dashboard.sidebarNotifications': 'Notificaciones',
    'dashboard.sidebarSettings': 'Configuración',
    'dashboard.signOut': 'Cerrar sesión',
    'dashboard.welcome': '¡Bienvenido de nuevo, John!',
    'dashboard.summary': 'Aquí está lo que pasa con tu viaje',
    'dashboard.totalTrips': 'Viajes totales',
    'dashboard.upcoming': 'Próximos',
    'dashboard.skymiles': 'SkyMiles',
    'dashboard.rewards': 'Recompensas',
    'dashboard.myTrips': 'Mis viajes',
    'dashboard.viewAll': 'Ver todo',
    'dashboard.upcomingLabel': 'Próximo',
    'dashboard.completedLabel': 'Completado',
    'dashboard.notifications': 'Notificaciones',
    'dashboard.adminTitle': 'Panel de administración',
    'dashboard.adminSubtitle': 'Gestiona tus operaciones aéreas',
    'dashboard.last30Days': 'Últimos 30 días',
    'dashboard.tabOverview': 'Resumen',
    'dashboard.tabFlights': 'Vuelos',
    'dashboard.tabBookings': 'Reservas',
    'dashboard.tabCustomers': 'Clientes',
    'dashboard.tabSettings': 'Configuración',
    'dashboard.revenueOverview': 'Resumen de ingresos',
    'dashboard.cabinDistribution': 'Distribución de cabina',
    'dashboard.topRoutes': 'Rutas principales',
    'dashboard.recentBookings': 'Reservas recientes',
    'dashboard.search': 'Buscar...',
    'dashboard.bookingId': 'ID de reserva',
    'dashboard.route': 'Ruta',
    'dashboard.date': 'Fecha',
    'dashboard.passengers': 'Pasajeros',
    'dashboard.status': 'Estado',
    'dashboard.amount': 'Monto',
    'dashboard.flightManagement': 'Gestión de vuelos',
    'dashboard.flightManagementSubtitle': 'Monitorea la flota y el rendimiento del horario',
    'dashboard.noResults': 'No se encontraron resultados',
    'flights.sortCheapest': 'Más barato',
    'flights.sortFastest': 'Más rápido',
    'flights.sortBestValue': 'Mejor relación',
    'flights.stops': 'Escalas',
    'flights.nonStop': 'Sin escalas',
    'flights.oneStop': '1 escala',
    'flights.multiStop': '2+ escalas',
    'flights.priceRange': 'Rango de precio',
    'flights.airlines': 'Aerolíneas',
    'flights.cabinClass': 'Clase de cabina',
    'flights.bookingOptions': 'Opciones de reserva',
    'flights.refundableOnly': 'Sólo reembolsables',
    'flights.modifySearch': 'Modificar búsqueda',
    'flights.flightsFound': 'vuelos encontrados',
    'flights.filters': 'Filtros',
    'flights.perPerson': 'por persona',
    'flights.select': 'Seleccionar',
    'flights.noFlights': 'Ningún vuelo coincide con tus filtros',
    'flights.clearFilters': 'Borrar todos los filtros',
    'flights.seatsLeft': 'asientos disponibles',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.flights': 'Vols',
    'nav.destinations': 'Destinations',
    'nav.deals': 'Offres',
    'nav.services': 'Services',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.signIn': 'Se connecter',
    'nav.orderNow': 'Commander',
    'nav.dashboard': 'Tableau de bord',
    'nav.signUp': 'S’inscrire',
    'nav.lightMode': 'Mode clair',
    'nav.darkMode': 'Mode sombre',
    'nav.langLabel': 'FR',
    'nav.language': 'Langue',
    'nav.languageSubtitle': 'Choisissez votre langue préférée',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'footer.fly': 'Voyager',
    'footer.experience': 'Expérience',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.bookFlight': 'Réserver un vol',
    'footer.flightStatus': 'Statut du vol',
    'footer.checkIn': 'Enregistrement',
    'footer.cabins': 'Cabines',
    'footer.dining': 'Restauration',
    'footer.entertainment': 'Divertissement',
    'footer.lounges': 'Salons',
    'footer.helpCenter': 'Centre d’aide',
    'footer.contactUs': 'Nous contacter',
    'footer.baggageInfo': 'Informations bagages',
    'footer.specialAssistance': 'Assistance spéciale',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d’utilisation',
    'footer.cookie': 'Politique des cookies',
    'footer.rights': '© 2025 SkyLux Airlines. Tous droits réservés.',
    'footer.privacyShort': 'Confidentialité',
    'footer.termsShort': 'Conditions',
    'footer.cookiesShort': 'Cookies',
    'footer.sitemap': 'Plan du site',
    'hero.badge': 'Manifeste validé // Matrice aérienne de niveau 1',
    'hero.titleLine1': 'Élevez votre',
    'hero.titleLine2': 'transport',
    'hero.highlight': 'global',
    'hero.subtitle': 'Proposez des itinéraires commerciaux dynamiques sur plus de 500 compagnies premium. Accès sécurisé aux réservations avec exécution personnalisée de trajets multicity.',
    'destinations.eyebrow': 'Populaire',
    'destinations.title': 'Découvrez les destinations qui montent',
    'destinations.subtitle': 'Des villes sélectionnées par nos voyageurs cette saison.',
    'destinations.from': 'À partir de',
    'deals.eyebrow': 'Temps limité',
    'deals.title': 'Offres à ne pas manquer',
    'deals.endsIn': 'Se termine dans',
    'deals.from': 'De',
    'deals.to': 'À',
    'deals.bookNow': 'Réserver',
    'features.eyebrow': 'Fonctionnalités entreprise',
    'features.title': 'Voler plus intelligemment',
    'features.subtitle': 'Tout ce dont vous avez besoin pour un voyage de luxe sans friction — conçu pour les voyageurs modernes.',
    'features.placeholder': 'Rechercher des capacités...',
    'features.showing': 'Affichage',
    'features.of': 'sur',
    'features.options': 'options',
    'features.collapse': 'Réduire la vue',
    'features.viewAll': 'Voir toutes les capacités',
    'features.none': 'Aucune fonctionnalité entreprise trouvée pour',
    'about.eyebrow': 'À propos',
    'about.title': 'Une façon plus intelligente de voler',
    'about.subtitle': 'SkyLux a été fondée en 2018 pour rendre les voyages de classe mondiale accessibles. Aujourd’hui, nous servons plus de 2M+ voyageurs dans 190 pays avec une obsession du détail et du design.',
    'about.travelers': 'Voyageurs',
    'about.partners': 'Partenaires aérien',
    'about.countries': 'Pays',
    'contact.eyebrow': 'Contact',
    'contact.title': 'Nous sommes là 24/7',
    'contact.subtitle': 'Contactez notre équipe concierge à tout moment — nous répondons généralement en moins de 5 minutes.',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.hq': 'Siège',
    'contact.firstName': 'Prénom',
    'contact.lastName': 'Nom',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'services.eyebrow': 'Services',
    'services.title': 'Des expériences premium, adaptées à vous',
    'services.subtitle': 'Du prioritaires à l’embarquement jusqu’aux itinéraires sur mesure, tout est pensé autour de votre voyage.',
    'notFound.title': 'Page introuvable',
    'notFound.subtitle': 'La page que vous recherchez n’existe pas ou a été déplacée.',
    'notFound.home': 'Retour à l’accueil',
    'auth.loginTitle': 'Bon retour',
    'auth.loginSubtitle': 'Connectez-vous à votre compte SkyLux',
    'auth.orContinue': 'ou continuez avec votre e-mail',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.signIn': 'Se connecter',
    'auth.noAccount': 'Vous n’avez pas de compte ?',
    'auth.signUp': 'S’inscrire',
    'auth.createAccountTitle': 'Créer un compte',
    'auth.createAccountSubtitle': 'Rejoignez SkyLux pour des avantages exclusifs',
    'auth.orSignUpWithEmail': 'ou inscrivez-vous par e-mail',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.passwordHint1': 'Au moins 8 caractères',
    'auth.passwordHint2': 'Une lettre majuscule',
    'auth.passwordHint3': 'Un chiffre',
    'auth.termsPrefix': 'J’accepte les',
    'auth.termsLink': 'Conditions d’utilisation',
    'auth.privacyLink': 'Politique de confidentialité',
    'auth.createAccount': 'Créer un compte',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte ?',
    'auth.signInLink': 'Se connecter',
    'dashboard.member': 'Membre SkyLux',
    'dashboard.sidebarTrips': 'Mes voyages',
    'dashboard.sidebarUpcoming': 'Vols à venir',
    'dashboard.sidebarRewards': 'Récompenses',
    'dashboard.sidebarPassengers': 'Passagers enregistrés',
    'dashboard.sidebarPayments': 'Paiements',
    'dashboard.sidebarNotifications': 'Notifications',
    'dashboard.sidebarSettings': 'Paramètres',
    'dashboard.signOut': 'Se déconnecter',
    'dashboard.welcome': 'Bon retour, John !',
    'dashboard.summary': 'Voici ce qui se passe avec votre voyage',
    'dashboard.totalTrips': 'Total des voyages',
    'dashboard.upcoming': 'À venir',
    'dashboard.skymiles': 'SkyMiles',
    'dashboard.rewards': 'Récompenses',
    'dashboard.myTrips': 'Mes voyages',
    'dashboard.viewAll': 'Voir tout',
    'dashboard.upcomingLabel': 'À venir',
    'dashboard.completedLabel': 'Terminé',
    'dashboard.notifications': 'Notifications',
    'dashboard.adminTitle': 'Tableau de bord administrateur',
    'dashboard.adminSubtitle': 'Gérez vos opérations aériennes',
    'dashboard.last30Days': 'Les 30 derniers jours',
    'dashboard.tabOverview': 'Aperçu',
    'dashboard.tabFlights': 'Vols',
    'dashboard.tabBookings': 'Réservations',
    'dashboard.tabCustomers': 'Clients',
    'dashboard.tabSettings': 'Paramètres',
    'dashboard.revenueOverview': 'Aperçu des revenus',
    'dashboard.cabinDistribution': 'Répartition des cabines',
    'dashboard.topRoutes': 'Routes principales',
    'dashboard.recentBookings': 'Réservations récentes',
    'dashboard.search': 'Rechercher...',
    'dashboard.bookingId': 'ID de réservation',
    'dashboard.route': 'Route',
    'dashboard.date': 'Date',
    'dashboard.passengers': 'Passagers',
    'dashboard.status': 'Statut',
    'dashboard.amount': 'Montant',
    'dashboard.flightManagement': 'Gestion des vols',
    'dashboard.flightManagementSubtitle': 'Surveillez la flotte et la performance des horaires',
    'dashboard.noResults': 'Aucun résultat trouvé',
    'flights.sortCheapest': 'Moins cher',
    'flights.sortFastest': 'Le plus rapide',
    'flights.sortBestValue': 'Meilleur rapport qualité/prix',
    'flights.stops': 'Escales',
    'flights.nonStop': 'Direct',
    'flights.oneStop': '1 escale',
    'flights.multiStop': '2+ escales',
    'flights.priceRange': 'Fourchette de prix',
    'flights.airlines': 'Compagnies aériennes',
    'flights.cabinClass': 'Classe de cabine',
    'flights.bookingOptions': 'Options de réservation',
    'flights.refundableOnly': 'Remboursable uniquement',
    'flights.modifySearch': 'Modifier la recherche',
    'flights.flightsFound': 'vols trouvés',
    'flights.filters': 'Filtres',
    'flights.perPerson': 'par personne',
    'flights.select': 'Sélectionner',
    'flights.noFlights': 'Aucun vol ne correspond à vos filtres',
    'flights.clearFilters': 'Effacer tous les filtres',
    'flights.seatsLeft': 'places restantes',
  },
  de: {
    'nav.langLabel': 'DE',
    'nav.language': 'Sprache',
    'nav.languageSubtitle': 'Wählen Sie Ihre bevorzugte Sprache',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Französisch',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Portugiesisch',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Startseite',
    'nav.flights': 'Flüge',
    'nav.destinations': 'Reiseziele',
    'nav.deals': 'Angebote',
    'nav.services': 'Dienstleistungen',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.signIn': 'Anmelden',
    'nav.orderNow': 'Jetzt buchen',
    'nav.dashboard': 'Dashboard',
    'nav.signUp': 'Registrieren',
    'nav.lightMode': 'Heller Modus',
    'nav.darkMode': 'Dunkler Modus',
  },
  pt: {
    'nav.langLabel': 'PT',
    'nav.language': 'Idioma',
    'nav.languageSubtitle': 'Escolha o seu idioma preferido',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Início',
    'nav.flights': 'Voos',
    'nav.destinations': 'Destinos',
    'nav.deals': 'Ofertas',
    'nav.services': 'Serviços',
    'nav.about': 'Sobre nós',
    'nav.contact': 'Contato',
    'nav.signIn': 'Entrar',
    'nav.orderNow': 'Reserve agora',
    'nav.dashboard': 'Painel',
    'nav.signUp': 'Cadastre-se',
    'nav.lightMode': 'Modo claro',
    'nav.darkMode': 'Modo escuro',
  },
  ar: {
    'nav.langLabel': 'AR',
    'nav.language': 'اللغة',
    'nav.languageSubtitle': 'اختر لغتك المفضلة',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'الرئيسية',
    'nav.flights': 'الرحلات',
    'nav.destinations': 'الوجهات',
    'nav.deals': 'العروض',
    'nav.services': 'الخدمات',
    'nav.about': 'من نحن',
    'nav.contact': 'تواصل معنا',
    'nav.signIn': 'تسجيل الدخول',
    'nav.orderNow': 'احجز الآن',
    'nav.dashboard': 'لوحة التحكم',
    'nav.signUp': 'إنشاء حساب',
    'nav.lightMode': 'الوضع الفاتح',
    'nav.darkMode': 'الوضع الداكن',
  },
  zh: {
    'nav.langLabel': '中文',
    'nav.language': '语言',
    'nav.languageSubtitle': '选择您偏好的语言',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': '首页',
    'nav.flights': '航班',
    'nav.destinations': '目的地',
    'nav.deals': '优惠',
    'nav.services': '服务',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.signIn': '登录',
    'nav.orderNow': '立即预订',
    'nav.dashboard': '控制面板',
    'nav.signUp': '注册',
    'nav.lightMode': '浅色模式',
    'nav.darkMode': '深色模式',
  },
  it: {
    'nav.langLabel': 'IT',
    'nav.language': 'Lingua',
    'nav.languageSubtitle': 'Scegli la tua lingua preferita',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Voli',
    'nav.destinations': 'Destinazioni',
    'nav.deals': 'Offerte',
    'nav.services': 'Servizi',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatti',
    'nav.signIn': 'Accedi',
    'nav.orderNow': 'Prenota ora',
    'nav.dashboard': 'Dashboard',
    'nav.signUp': 'Registrati',
    'nav.lightMode': 'Modalità chiara',
    'nav.darkMode': 'Modalità scura',
  },
  nl: {
    'nav.langLabel': 'NL',
    'nav.language': 'Taal',
    'nav.languageSubtitle': 'Kies je voorkeurstaal',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Vluchten',
    'nav.destinations': 'Bestemmingen',
    'nav.deals': 'Aanbiedingen',
    'nav.services': 'Services',
    'nav.about': 'Over ons',
    'nav.contact': 'Contact',
    'nav.signIn': 'Inloggen',
    'nav.orderNow': 'Nu reserveren',
    'nav.dashboard': 'Dashboard',
    'nav.signUp': 'Registreren',
    'nav.lightMode': 'Lichte modus',
    'nav.darkMode': 'Donkere modus',
  },
  tr: {
    'nav.langLabel': 'TR',
    'nav.language': 'Dil',
    'nav.languageSubtitle': 'Tercih ettiğiniz dili seçin',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Uçuşlar',
    'nav.destinations': 'Destinasyonlar',
    'nav.deals': 'Fırsatlar',
    'nav.services': 'Hizmetler',
    'nav.about': 'Hakkında',
    'nav.contact': 'İletişim',
    'nav.signIn': 'Oturum Aç',
    'nav.orderNow': 'Şimdi Rezervasyon Yap',
    'nav.dashboard': 'Kontrol Paneli',
    'nav.signUp': 'Kaydol',
    'nav.lightMode': 'Açık Mod',
    'nav.darkMode': 'Koyu Mod',
  },
  sv: {
    'nav.langLabel': 'SV',
    'nav.language': 'Språk',
    'nav.languageSubtitle': 'Välj ditt föredragna språk',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Flyg',
    'nav.destinations': 'Destinationer',
    'nav.deals': 'Erbjudanden',
    'nav.services': 'Tjänster',
    'nav.about': 'Om oss',
    'nav.contact': 'Kontakt',
    'nav.signIn': 'Logga in',
    'nav.orderNow': 'Boka nu',
    'nav.dashboard': 'Kontrollpanel',
    'nav.signUp': 'Registrera dig',
    'nav.lightMode': 'Ljust läge',
    'nav.darkMode': 'Mörkt läge',
  },
  ru: {
    'nav.langLabel': 'RU',
    'nav.language': 'Язык',
    'nav.languageSubtitle': 'Выберите предпочитаемый язык',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Рейсы',
    'nav.destinations': 'Пункты назначения',
    'nav.deals': 'Предложения',
    'nav.services': 'Услуги',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.signIn': 'Войти',
    'nav.orderNow': 'Забронировать сейчас',
    'nav.dashboard': 'Панель управления',
    'nav.signUp': 'Зарегистрироваться',
    'nav.lightMode': 'Светлый режим',
    'nav.darkMode': 'Тёмный режим',
  },
  hi: {
    'nav.langLabel': 'HI',
    'nav.language': 'भाषा',
    'nav.languageSubtitle': 'अपनी पसंदीदा भाषा चुनें',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'उड़ानें',
    'nav.destinations': 'गंतव्य',
    'nav.deals': 'ऑफर',
    'nav.services': 'सेवाएं',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.signIn': 'साइन इन करें',
    'nav.orderNow': 'अभी बुक करें',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.signUp': 'साइन अप करें',
    'nav.lightMode': 'लाइट मोड',
    'nav.darkMode': 'डार्क मोड',
  },
  ja: {
    'nav.langLabel': 'JA',
    'nav.language': '言語',
    'nav.languageSubtitle': 'お好みの言語を選択してください',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'フライト',
    'nav.destinations': '目的地',
    'nav.deals': 'ディール',
    'nav.services': 'サービス',
    'nav.about': 'について',
    'nav.contact': 'お問い合わせ',
    'nav.signIn': 'サインイン',
    'nav.orderNow': '今すぐ予約',
    'nav.dashboard': 'ダッシュボード',
    'nav.signUp': 'サインアップ',
    'nav.lightMode': 'ライトモード',
    'nav.darkMode': 'ダークモード',
  },
  ko: {
    'nav.langLabel': 'KO',
    'nav.language': '언어',
    'nav.languageSubtitle': '선호하는 언어를 선택하세요',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': '항공편',
    'nav.destinations': '목적지',
    'nav.deals': '거래',
    'nav.services': '서비스',
    'nav.about': '정보',
    'nav.contact': '연락처',
    'nav.signIn': '로그인',
    'nav.orderNow': '지금 예약',
    'nav.dashboard': '대시보드',
    'nav.signUp': '가입',
    'nav.lightMode': '라이트 모드',
    'nav.darkMode': '다크 모드',
  },
  vi: {
    'nav.langLabel': 'VI',
    'nav.language': 'Ngôn ngữ',
    'nav.languageSubtitle': 'Chọn ngôn ngữ ưa thích của bạn',
    'nav.languageEnglish': 'English',
    'nav.languageSpanish': 'Español',
    'nav.languageFrench': 'Français',
    'nav.languageGerman': 'Deutsch',
    'nav.languagePortuguese': 'Português',
    'nav.languageArabic': 'العربية',
    'nav.languageChinese': '中文',
    'nav.home': 'Home',
    'nav.flights': 'Các chuyến bay',
    'nav.destinations': 'Điểm đến',
    'nav.deals': 'Ưu đãi',
    'nav.services': 'Dịch vụ',
    'nav.about': 'Về chúng tôi',
    'nav.contact': 'Liên hệ',
    'nav.signIn': 'Đăng nhập',
    'nav.orderNow': 'Đặt ngay',
    'nav.dashboard': 'Bảng điều khiển',
    'nav.signUp': 'Đăng ký',
    'nav.lightMode': 'Chế độ sáng',
    'nav.darkMode': 'Chế độ tối',
  },
};

export function UiProvider({ children }: { children: React.ReactNode }) {
  const [theme, setThemeState] = useState<ThemeMode>(() => {
    if (typeof window === 'undefined') return 'light';
    const storedTheme = window.localStorage.getItem('theme');
    if (storedTheme === 'light' || storedTheme === 'dark') return storedTheme;
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  });
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const storedLanguage = window.localStorage.getItem('language');
    if (storedLanguage && ['es', 'fr', 'de', 'pt', 'ar', 'zh'].includes(storedLanguage)) {
      return storedLanguage as Language;
    }
    return 'en';
  });

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.style.colorScheme = theme;
    window.localStorage.setItem('theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    window.localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo<UiContextValue>(
    () => ({
      theme,
      toggleTheme: () => setThemeState((current) => (current === 'dark' ? 'light' : 'dark')),
      setTheme: (nextTheme) => setThemeState(nextTheme),
      language,
      setLanguage: (nextLanguage) => setLanguageState(nextLanguage),
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language, theme],
  );

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  const context = useContext(UiContext);
  if (!context) {
    throw new Error('useUi must be used inside UiProvider');
  }
  return context;
}
